### ISSUE TITLE
Remove "Description" from the Model

### ISSUE THREAD

**Issue by ktos** [csplb/CatApi#15]
The "Description" field is not used (and it seems is always null), so it should be removed from the Model and not presented to any client.

Additionally, it may be removed from all entries in `cats.json` database.

**Comment by marty-shields** [comment]
I'll have a look at this - I have sent a PR, does not look like I can link this for some reason

**Comment by ktos** [comment]
Merged. I haven't noticed it is actually only in this one place :)

Still, `cats.json` needs to be updated sometime.

**Comment by marty-shields** [comment]
Apologies, leave the issue open, I will resolve. That's the only place I didn't check (I did check tests though)

**Comment by ktos** [comment]
Fixed in #20, thank you very much! :)
